Seguridad
nicolasolivera32/rollingbankT1 pull request #3
Opened 2023-10-14 21:56 UTC by nicolasolivera32

2023-10-16 16:30 UTC, julianDev94 commented on pages/seguridad.html
> +                <a class="nav-link" href="./pages/quienesSomos.html"
Cambiar dirección de las rutas

2023-10-16 16:31 UTC, julianDev94 requested changes
Nico, fíjate de cambiar la dirección de las rutas porque sale el error del get.

2023-10-16 16:42 UTC, julianDev94 requested changes
Cambia las rutas del footer para que se direccionen al error 404

2023-10-17 05:46 UTC, Elias-Juarez requested changes
quitar la clase show y agregar el collapsed en el ultimo div del acordion.

2023-10-17 06:31 UTC, Elias-Juarez approved these changes
ta bien

2023-10-17 06:32 UTC, merged