Quienes somos
nicolasolivera32/rollingbankT1 pull request #5
Opened 2023-10-16 23:15 UTC by cinn778

2023-10-17 05:03 UTC, Elias-Juarez requested changes
volver a crear la carpeta img, corregir las rutas de las imágenes y los enlaces, y el area current del navbar, cambiar los lorem.

2023-10-17 11:33 UTC, cinn778 commented
listorti, no sabia si tenia que ponerle el css tambien asi que lo puse

2023-10-18 04:34 UTC, Elias-Juarez requested changes
corregir la ruta de rollingbank en el navbar

2023-10-18 04:52 UTC, Elias-Juarez approved these changes
todo bien

2023-10-18 04:53 UTC, merged